SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE cart_items;
TRUNCATE TABLE shopping_carts;
TRUNCATE TABLE order_items;
TRUNCATE TABLE books_categories;
TRUNCATE TABLE books;
TRUNCATE TABLE categories;
TRUNCATE TABLE orders;
TRUNCATE TABLE users_roles;
TRUNCATE TABLE users;

SET REFERENTIAL_INTEGRITY TRUE;